name: Linux Tests

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential ninja-build python3

      - name: Run JSON regression suite
        run: bash tests/run_json_tests.sh

      - name: Upload dumps on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: linux-failing-dumps
          path: tests/json_cases/**/dump.json
